name: marvelflix
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_bloc: ^8.1.3
  dio: ^5.3.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.4
  animate_do: ^3.1.2
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  video_player: ^2.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/marvel.png
    - assets/icons/menu_icon.svg
    - assets/icons/notification_icon.svg


  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/google_fonts/worksans/WorkSans-Bold.ttf
        - asset: assets/google_fonts/worksans/WorkSans-Regular.ttf
          
    - family: Merriweather
      fonts:
        - asset: assets/google_fonts/merriweather/Merriweather-Black.ttf
        - asset: assets/google_fonts/merriweather/Merriweather-Bold.ttf

    - family: Mulish
      fonts:
        - asset: assets/google_fonts/mulish/Mulish-Bold.ttf
        - asset: assets/google_fonts/mulish/Mulish-Regular.ttf
